source 'https://rubygems.org'
ruby '2.3.0'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'execjs'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'paranoia'
gem 'quiet_assets'
gem 'bootstrap-sass'
gem 'sprockets-rails'
gem 'therubyracer'
gem 'sidekiq'
gem 'tokens'
gem 'bcrypt'
gem 'settingslogic'
gem 'validates_email_format_of'
gem 'rails-i18n'

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'web-console', '~> 2.0'
  gem 'annotate'
  gem 'dotenv-rails', github: 'bkeepers/dotenv'
  gem 'spring'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'capybara'
  gem 'capybara-email'
  gem 'poltergeist'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'gimei'
  gem 'json_spec'
  gem 'rspec-json_matcher', require: false
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'database_rewinder'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'growl'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'hirb'
  gem 'bullet'
  gem 'simplecov'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers', ">= 3.0.0", require: false
  gem 'timecop'
  gem 'rack-cors'
  gem 'letter_opener'
  gem 'letter_opener_web'
end
